### ISSUE TITLE
bug: getCurrentUser doesn't work with Firebase 9.9.3

### ISSUE THREAD

**Issue by DeveloperAdam-github** [capawesome-team/capacitor-firebase#187]
I have all the auth set up and actually works fine, I understand there is an issue with getAuth() not working so have added a fix which doesn't resolve anything. So I use the `FirebaseAuthenetication.getCurrentUser()` & `FirebaseAuthenetication.getIdToken()` to TRY and run the updateProfile() from Firebase itself but use the plugin functions instead however it seems Firebase doesn't recognise the getCurrentUser() and I get this error **TypeError: userInternal.getIdToken is not a function**

```
"import { getAuth, updateProfile } from "firebase/auth";
const auth = getAuth();
updateProfile(auth.currentUser, {
  displayName: "Jane Q. User", photoURL: "https://example.com/jane-q-user/profile.jpg"
}).then(() => {
  // Profile updated!
  // ...
}).catch((error) => {
  // An error occurred
  // ...
});"
```

```
function whichAuth() {
  let auth;
  if (Capacitor.isNativePlatform()) {
    auth = initializeAuth(app, {
      persistence: indexedDBLocalPersistence,
    });
  } else {
    auth = getAuth(app);
  }
  return auth;
}
```

**Plugin(s):**

**Platform(s):**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Please provide a minimal, reproducible example so I can debug your issue.
